spring:
  profiles:
    active: local
  application:
    name: local_sso
server:
  port: 8081
db:
  app:
    datasource:
      driver-class: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5101/sso_local
      user: pt
      password: abc
      properties:
        ssl: 'false'
        sslmode: 'disable'
  token:
    datasource:
      driver-class: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5101/sso_token
      user: pt
      password: abc
      properties:
        ssl: 'false'
        sslmode: 'disable'